name: Build & Deploy
on:
  push:
    branches: [ main, sepln-dev ]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: pdflatex Thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis.tex
          working_directory: document
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex Thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis
          working_directory: document
          compiler: biber
          args: 
      - name: pdflatex Thesis
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis.tex
          working_directory: document
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: pdflatex Presentation
        uses: dante-ev/latex-action@latest
        with:
          root_file: Presentation.tex
          working_directory: presentation
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: pdflatex template-sepln
        uses: dante-ev/latex-action@latest
        with:
          root_file: EjemploARTsepln.tex
          working_directory: sepln
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex template-sepln
        uses: dante-ev/latex-action@latest
        with:
          root_file: EjemploARTsepln
          working_directory: sepln
          # compiler: biber
          compiler: bibtex
          args: 
      - name: pdflatex template-sepln
        uses: dante-ev/latex-action@latest
        with:
          root_file: EjemploARTsepln.tex
          working_directory: sepln
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: pdflatex template-sepln
        uses: dante-ev/latex-action@latest
        with:
          root_file: EjemploARTsepln.tex
          working_directory: sepln
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: Prepare for Deploy
        run: |
          mkdir build
          mv document/Thesis.pdf build/document.pdf
          mv presentation/Presentation.pdf build/presentation.pdf
          mv sepln/EjemploARTsepln.pdf build/sepln.pdf
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
